//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbarWebService.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://maugarciaapps.tech/", ConfigurationName="ServiceReference1.GetConsulta_MontoOrdenesSoap")]
    public interface GetConsulta_MontoOrdenesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maugarciaapps.tech/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maugarciaapps.tech/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maugarciaapps.tech/GetConsultaMontoOrdenes_", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConsultaMontoOrdenes_();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maugarciaapps.tech/GetConsultaMontoOrdenes_", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConsultaMontoOrdenes_Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetConsulta_MontoOrdenesSoapChannel : ProbarWebService.ServiceReference1.GetConsulta_MontoOrdenesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetConsulta_MontoOrdenesSoapClient : System.ServiceModel.ClientBase<ProbarWebService.ServiceReference1.GetConsulta_MontoOrdenesSoap>, ProbarWebService.ServiceReference1.GetConsulta_MontoOrdenesSoap {
        
        public GetConsulta_MontoOrdenesSoapClient() {
        }
        
        public GetConsulta_MontoOrdenesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetConsulta_MontoOrdenesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetConsulta_MontoOrdenesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetConsulta_MontoOrdenesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetConsultaMontoOrdenes_() {
            return base.Channel.GetConsultaMontoOrdenes_();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConsultaMontoOrdenes_Async() {
            return base.Channel.GetConsultaMontoOrdenes_Async();
        }
    }
}
